yml file changed

diff --git a/.github/workflows/cypress-allure.yml b/.github/workflows/cypress-allure.yml
--- a/.github/workflows/cypress-allure.yml
+++ b/.github/workflows/cypress-allure.yml
@@ -3,7 +3,7 @@ name: Cypress Tests with Allure Report
 on:
   push:
     branches:
-      - main # Replace 'main' with your desired branch name
+      - main  # Replace 'main' with your desired branch name
 
 jobs:
   cypress-run:
@@ -29,7 +29,7 @@ jobs:
         run: |
           npm install -g allure-commandline --save-dev # Install Allure
           npx cypress run --browser=chrome --headed --spec "cypress/e2e/**/*.cy.js" --reporter mocha-allure-reporter
-        continue-on-error: true # Allows workflow to proceed even if this step fails
+        continue-on-error: true  # Allows workflow to proceed even if this step fails
 
       # Step 5: Generate Allure Report (Runs always, regardless of previous steps' success)
       - name: Generate Allure Report
@@ -37,22 +37,22 @@ jobs:
         run: |
           npx allure generate allure-results --clean -o allure-report
 
-      # Step 6: Publish Allure report using GitHub Pages (Runs always, regardless of previous steps' success)
+      # Step 6: Clean up gh-pages branch before publishing
+      - name: Cleanup gh-pages branch
+        if: always()
+        run: |
+          git fetch origin gh-pages
+          git checkout gh-pages || git checkout --orphan gh-pages
+          git rm -rf .
+          git commit -m "Cleanup old reports" || echo "No changes to commit"
+          git push origin gh-pages
+
+      # Step 7: Publish Allure report using GitHub Pages
       - name: Deploy Allure Report to GitHub Pages
         if: always() # Ensures this step runs even if the Cypress tests fail
         uses: peaceiris/actions-gh-pages@v3
         with:
           github_token: ${{ secrets.GHTOKEN }}
           publish_dir: ./allure-report
-          publish_branch: gh-pages # Specify the branch to use for GitHub Pages
-          force_orphan: true # Force-create a new commit without history
-
-        # Step 7: Clean up gh-pages branch before publishing
-      - name: Cleanup gh-pages branch
-        if: always()
-        run: |
-          git fetch origin gh-pages
-          git checkout gh-pages
-          git rm -rf .
-          git commit -m "Cleanup old reports"
-          git push origin gh-pages
+          publish_branch: gh-pages  # Specify the branch to use for GitHub Pages
+          force_orphan: true        # Force-create a new commit without history
